from .connected_robot_endpoints.routes import connected_robot_bp
from .connected_user_endpoints.routes import connected_user_bp
from .mission_endpoints.routes import mission_bp
from .qr_code_endpoints.routes import qr_code_bp
from .road_map_endpoints.routes import road_map_bp
from .robot_endpoints.routes import robot_bp
from .robot_location_endpoints.routes import robot_location_bp
from .room_endpoints.routes import room_bp
from .turn_point_endpoints.routes import turn_point_bp
from .user_endpoints.routes import user_bp
